### ISSUE TITLE
[BUG] Heimdall page broken 

### ISSUE THREAD

**Issue by arces** [linuxserver/docker-heimdall#143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My Heimdall docker image updated to the latest version "Linuxserver.io version:- V2.5.8-ls252 Build-date:- 2024-02-16T18:30:28+00:00" via watchtower.
When I open it, I get the following: 

```
@extends('layouts.app') @section('content') @include('partials.search') @if($apps->first()) @include('sortable') @else
{!! __('app.dash.no_apps', [ 'link1' => '['.__('app.dash.link1').'](https://MY_URL_HERE/'.route('items.create',%20[]).')', 'link2' => '['.__('app.dash.link2').'](https://MY_URL_HERE/)' ]) !!}

@include('add')
@endif @endsection

```
![image](https://github.com/linuxserver/docker-heimdall/assets/3622441/71c53bd4-1cee-44f4-94b5-dc6d4d530d20)

Tried the page in incognito, hard refresh/empty cache, cleared out browser storage, recreated the image with a freshly pulled image

### Steps To Reproduce

Update to the latest version
Launch with portainer/docker

### Environment

```markdown
- OS: Ubuntu 20.04
- How docker service was installed:
Portainer stack

Stack:
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /var/lib/docker/volumes/heimdall/_data:/config
    ports:
      - 8081:80
      - 4443:443
    restart: unless-stopped
```

### CPU architecture

x86-64

### Docker creation

```bash
I just pulled the latest image and used my existing configs. Using Portainer Stacks, which is just docker compose as far as I know.
```

### Container logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1000
───────────────────────────────────────
using keys found in /config/keys
New container detected, installing Heimdall
**** The following active confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
│  old date  │  new date  │ path                                                                   │
├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
│            │ 2023-04-13 │ /config/nginx/nginx.conf                                               │
│ 2022-08-20 │ 2023-08-13 │ /config/nginx/ssl.conf                                                 │
│ 2018-03-06 │ 2023-04-13 │ /config/nginx/site-confs/default.conf                                  │
└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by Neriderc** [comment]
Just commenting to say I'm having the same issue!

```
@extends('layouts.app') @section('content') @include('partials.search') @if($apps->first()) @include('sortable') @else

{!! __('app.dash.no_apps', [ 'link1' => '['.__('app.dash.link1').'](http://192.168.1.10:8080/'.route('items.create',%20[]).')', 'link2' => '['.__('app.dash.link2').'](http://192.168.1.10:8080/)' ]) !!}
@include('add')
@endif @endsection
```

I have removed the ./config directory and tried it fresh, accessing it directly by port not through the reverse proxy, and it still doesn't work.

**Comment by dakink** [comment]
+1. New pull and fresh config directory don't seem to help. Reverting to tag 2.5.7 solves the issue for me.

**Comment by Neriderc** [comment]
> +1. New pull and fresh config directory don't seem to help. Reverting to tag 2.5.7 solves the issue for me.

I can confirm this worked for me too.

**Comment by grpfl** [comment]
Same issue, and reverting to 2.5.7 resolved it

**Comment by bb12489** [comment]
Same issue here. Reverting helped me as well.

**Comment by pokrzys** [comment]
Same problem. Reverting to V2.5.8-ls251 solves it. No need to go back to 2.5.7.

**Comment by dakink** [comment]
> Same problem. Reverting to V2.5.8-ls251 solves it. No need to go back to 2.5.7.

Jip, this one works as well.

**Comment by unixweb** [comment]
docker pull linuxserver/heimdall:amd64-V2.5.8-ls250 works in my case

**Comment by arces** [comment]
Any thoughts @thespad ?

**Comment by j0nnymoe** [comment]
> Any thoughts @thespad ?

Roll back to the working image mentioned, fixed build should be out within 24 hours.

**Comment by KodeStar** [comment]
Fixed build has been out for a couple of days

**Comment by borracho-mejor** [comment]
This issue still exists with the `:latest` tag, I've been updating my `docker-compose.yml` each week to repull the latest issue and it consistently breaks until I revert to `2.6.1`. Is there going to be a planned fix for this in later versions? I see the exact same text as in the screenshots.

**Comment by arces** [comment]
> This issue still exists with the `:latest` tag, I've been updating my `docker-compose.yml` each week to repull the latest issue and it consistently breaks until I revert to `2.6.1`. Is there going to be a planned fix for this in later versions? I see the exact same text as in the screenshots.

I had the same issue too. What I did (I use portainer) was redeploy the image and pull a fresh copy of it and it worked! I am not exactly sure, but I used the same old configs and data from my past versions. Just updated my stack (in portainer) and then manually went to the running container and had it pull a fresh image. Hard refreshed on my browser and it was back up and running just like normal

**Comment by fjmerc** [comment]
I can confirm that @arces recommendation to redeploy the image worked for me. I had to first remove the image(s) by running docker image rm --force <image_id> and then redeploy my stack.
